### PR TITLE
Make holmes python installable

### PR DESCRIPTION
**Pull request by aantn**
Move contents of holmes.py to holmes/main.py. This is necesssary to make the entrypoint installable.

Note: this includes changes from #56 as well, so will be easier to review once that is merged. (I didn't base this PR off master as that would have caused conflicts once #56 is merged as they both touch holmes.py.)

### CODE REVIEW

**Comment by Avi-Robusta** [comment]
I tried building it in pyinstaller to verify this doesnt break anything
This is the error I got when running it

```
Traceback (most recent call last):
  File "holmes.py", line 1, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "holmes/main.py", line 15, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "holmes/config.py", line 4, in <module>
ModuleNotFoundError: No module named 'strenum'
[47550] Failed to execute script 'holmes' due to unhandled exception!
```
could be an issue locally with me but release an alpha of this branch and test it before you merge

**Comment by aantn** [comment]
> I tried building it in pyinstaller to verify this doesnt break anything This is the error I got when running it
> 
> ```
> Traceback (most recent call last):
>   File "holmes.py", line 1, in <module>
>   File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
>   File "holmes/main.py", line 15, in <module>
>   File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
>   File "holmes/config.py", line 4, in <module>
> ModuleNotFoundError: No module named 'strenum'
> [47550] Failed to execute script 'holmes' due to unhandled exception!
> ```
> 
> could be an issue locally with me but release an alpha of this branch and test it before you merge

Can you try running poetry install and then trying again? strenum is a dependency that I added recently.

**Comment by Avi-Robusta** [comment]
I did poetry install again, still same issue, can you try building it in pyinstaller by you and running it?

**Review by Avi-Robusta — APPROVED** [review]
LGTM
- [ ] create alpha release of this branch and verify it runs before merging

**Comment by aantn** [comment]
There is some issue here with pyinstaller running outside of the virtualenv in an environment that is missing some of the dependencies. 

But I am pretty certain that the actual build will be fine, as it is being built and tested on this branch succesfully https://github.com/robusta-dev/holmesgpt/actions/runs/9631797244/job/26564056536?pr=57

Regardless, I will do a test release like you said and verify before we do a proper release! Nice catch.

**Pull request merged**
